# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-05 14:16
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0023_auto_20170607_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=350, verbose_name='Nombre y apellidos')),
                ('dni', models.CharField(max_length=30, verbose_name='Documento identidad')),
                ('is_underage', models.BooleanField(default=False, verbose_name='Menor de edad')),
            ],
            options={
                'ordering': ['band'],
                'verbose_name': 'Miembro de banda',
                'verbose_name_plural': 'Miembros de bandas',
            },
        ),
        migrations.CreateModel(
            name='ContestBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Nombre')),
                ('genre', models.CharField(blank=True, max_length=240, null=True, verbose_name='etiqueta')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('contest/'), verbose_name='Imagen principal')),
                ('band_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('contest/'), verbose_name='Imagen de cabecera')),
                ('city', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ciudad')),
                ('num_members', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('embed_code', models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed para escucha (Bandcamp, Soundcloud, Spotify...')),
                ('embed_media', models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed de v\xeddeo (Youtube, Vimeo...')),
                ('receiver_fullname', models.CharField(blank=True, max_length=350, null=True, verbose_name='Nombre')),
                ('receiver_cif', models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento identidad')),
                ('has_local_member', models.BooleanField(default=False, verbose_name='Miembros locales')),
                ('local_member_docs', models.FileField(max_length=180, null=True, upload_to=bands.helpers.RandomFileName('contest_docs/'), verbose_name='Documentaci\xf3n')),
                ('contact_email', models.CharField(max_length=250, verbose_name='Email de contacto')),
                ('contact_phone1', models.CharField(max_length=250, verbose_name='Email de contacto')),
                ('contact_phone2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email de contacto')),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina de Facebook')),
                ('youtube_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Canal de Youtube')),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Twitter')),
                ('bandcamp_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina de BandCamp')),
                ('presskit_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Presskit')),
                ('webpage_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina web')),
                ('spotify_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Spotify')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_bands', to='bands.Tag')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Banda concursante',
                'verbose_name_plural': 'Bandas concursantes',
            },
        ),
        migrations.AddField(
            model_name='bandmember',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Miembros', to='contest.ContestBand', verbose_name='Banda'),
        ),
    ]
