# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-06 12:30
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestband',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones/Comentarios'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='city',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ciudad de origen'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='contact_phone1',
            field=models.CharField(max_length=250, verbose_name='Tel\xe9fono de contacto'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tel\xe9fono de contacto (2)'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n/Biograf\xeda del grupo'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed para escucha (Bandcamp, Soundcloud, Spotify...)'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='embed_media',
            field=models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed de v\xeddeo (Youtube, Vimeo...)'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='genre',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='G\xe9nero/Estilo'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='local_member_docs',
            field=models.FileField(blank=True, max_length=180, null=True, upload_to=bands.helpers.RandomFileName('contest_docs/'), verbose_name='Documentaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Nombre de la banda/solista'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='num_members',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='N\xfamero de miembros'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='receiver_cif',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento (DNI/NIF/CIF)'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='receiver_fullname',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Nombre de interesado'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_bands', to='bands.Tag', verbose_name='Categor\xeda del concurso'),
        ),
    ]
