# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-06 18:03
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20180406_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestband',
            name='rider_doc',
            field=models.FileField(blank=True, max_length=180, upload_to=bands.helpers.RandomFileName('contest_docs/'), verbose_name='Rider t\xe9cnico (adjuntar)'),
        ),
    ]
