# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0004_auto_20180413_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPublicVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Timestamp')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_votes', to='contest.ContestBand', verbose_name='Banda')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_votes', to=settings.AUTH_USER_MODEL, verbose_name='Votante')),
            ],
            options={
                'ordering': ['band'],
                'verbose_name': 'Voto del p\xfablico',
                'verbose_name_plural': 'Votos del p\xfablico',
            },
        ),
        migrations.AlterModelOptions(
            name='contestjuryvote',
            options={'ordering': ['band'], 'permissions': (('can_mange_jury', 'Puede acceder al jurado'),), 'verbose_name': 'Voto del jurado', 'verbose_name_plural': 'Votos del jurado'},
        ),
        migrations.AlterUniqueTogether(
            name='contestpublicvote',
            unique_together=set([('band', 'timestamp')]),
        ),
    ]
