# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20180417_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestband',
            name='criteria1',
            field=models.BooleanField(default=False, verbose_name='\xbfEl 50% de tus m\xfasicos o m\xe1s tienen menos de 21 a\xf1os?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria2',
            field=models.BooleanField(default=False, verbose_name='\xbfHas realizado al menos 2 conciertos en los \xfaltimos 6 meses?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria2_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Pega enlaces a alguna referencia web de los dos conciertos (evento en Fb, cr\xf3nica, anuncio...)'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria3',
            field=models.IntegerField(choices=[(0, 'Ninguna'), (2, '1'), (4, '2'), (6, '3'), (7, 'M\xe1s de tres')], default=0, verbose_name='\xbfCuantas mujeres componen tu formaci\xf3n?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria4',
            field=models.BooleanField(default=False, verbose_name='\xbfTienes alg\xfan \xe1lbum editado?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria4_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Pega alg\xfan enlace donde poder esucharlo: Spotify, Bandcamp, etc'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria5',
            field=models.BooleanField(default=False, verbose_name='\xbfTienes dossier de prensa?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria6',
            field=models.BooleanField(default=False, verbose_name='Tienes alguna cr\xf3nica o cr\xedtica en alg\xfan medio?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria6_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Pega enlaces a alguna referencia'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria7',
            field=models.BooleanField(default=False, verbose_name='\xbfTienes redes sociales activas?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria8',
            field=models.BooleanField(default=False, verbose_name='\xbfAl menos el 80% de tu repertorio son temas propios?'),
        ),
        migrations.AddField(
            model_name='contestband',
            name='criteria9',
            field=models.BooleanField(default=False, verbose_name='\xbfTocaste o estabas programado el a\xf1o pasado en Alcal\xe1 Suena?'),
        ),
    ]
