# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-25 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestband',
            name='criteria5',
            field=models.BooleanField(default=False, verbose_name='\xbfTienes dossier de tu banda?'),
        ),
    ]
