# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20190225_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestband',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram'),
        ),
    ]
