# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-27 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0009_contestband_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestband',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
    ]
