# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-05-14 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestband',
            name='criteria2',
            field=models.BooleanField(default=False, verbose_name='\xbfHas realizado al menos un concierto en el \xfaltimo a\xf1o?'),
        ),
        migrations.AlterField(
            model_name='contestband',
            name='criteria2_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Pega enlaces a alguna referencia web de los conciertos (evento en Fb, cr\xf3nica, anuncio...)'),
        ),
    ]
