# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-03 15:02
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.IntegerField(unique=True, verbose_name='A\xf1o')),
                ('main_logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('archive/'), verbose_name='Imagen cabecera')),
                ('bg_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('archive/'), verbose_name='Imagen de fondo')),
                ('main_color', models.CharField(default='#FFFFFFFF', max_length=10, verbose_name='Color principal')),
                ('front_color', models.CharField(default='#000000', max_length=10, verbose_name='Color texto principal')),
            ],
            options={
                'ordering': ['archive_year'],
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'A\xf1os archivados',
            },
        ),
    ]
