# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Nombre')),
                ('tag', models.TextField(verbose_name='etiqueta')),
                ('genre', models.TextField(verbose_name='etiqueta')),
                ('profile_image', models.ImageField(null=True, upload_to=b'')),
                ('band_image', models.ImageField(null=True, upload_to=b'')),
                ('city', models.TextField(verbose_name='Ciudad')),
                ('num_members', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('youtube_embed', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
            },
        ),
    ]
