# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_venue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=240, verbose_name='Etiqueta')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descrition', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#FFFFFFFF', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day', 'time'], 'verbose_name': 'Concierto', 'verbose_name_plural': 'Conciertos'},
        ),
        migrations.AlterField(
            model_name='band',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band', to='bands.Tag'),
        ),
    ]
