# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_auto_20170523_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
            ],
            options={
                'ordering': ['band'],
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
