# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 16:52
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_bandtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=models.ImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('band/')),
        ),
        migrations.AlterField(
            model_name='band',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('band/')),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('venue/')),
        ),
    ]
