# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_auto_20170523_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
