# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bandcamp_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina de BandCamp'),
        ),
        migrations.AddField(
            model_name='band',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina de Facebook'),
        ),
        migrations.AddField(
            model_name='band',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Twitter'),
        ),
        migrations.AddField(
            model_name='band',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Canal de Youtube'),
        ),
    ]
