# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_auto_20170524_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='presskit_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Presskit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bands.Band'),
        ),
    ]
