# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_auto_20170524_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='etiqueta'),
        ),
    ]
