# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_auto_20170525_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='num_members',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
