# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0016_auto_20170527_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='descrition',
            new_name='description',
        ),
    ]
