# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0017_auto_20170527_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name=b'identificador')),
                ('value', models.CharField(blank=True, max_length=240, null=True, verbose_name=b'valor')),
            ],
            options={
                'ordering': ['key'],
                'verbose_name': 'Configuraciones',
                'verbose_name_plural': 'Configuraci\xf3n',
            },
        ),
    ]
