# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0019_auto_20170602_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='caducity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
