# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:16
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0020_auto_20170602_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona de contacto')),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tel\xe9fono de contacto')),
                ('num_members', models.IntegerField(blank=True, default=1, null=True, verbose_name='N\xfamero de componentes')),
                ('billing_total', models.FloatField(blank=True, null=True, verbose_name='Importe TOTAL Factura')),
                ('billing_file', models.FileField(upload_to=bands.helpers.RandomFileName('bills/'))),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Venue', verbose_name='Escenario en el que tocaron')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
