# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:54
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0021_billinginfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginfo',
            options={'ordering': ['uploaded'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='cif',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='NIF/CIF'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band', verbose_name='Banda'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_file',
            field=models.FileField(upload_to=bands.helpers.RandomFileName('bills/'), verbose_name='Factura'),
        ),
    ]
