# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 12:55
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0023_auto_20170607_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='embed_media',
            field=models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed (enlace o iframe) de v\xeddeo (Youtube, Vimeo...)'),
        ),
        migrations.AddField(
            model_name='band',
            name='spotify_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Spotify'),
        ),
        migrations.AddField(
            model_name='band',
            name='webpage_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina web'),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('band/'), verbose_name='Imagen de cabecera'),
        ),
        migrations.AlterField(
            model_name='band',
            name='embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed (enlace o iframe) para escucha (Bandcamp, Soundcloud, Spotify...)'),
        ),
        migrations.AlterField(
            model_name='band',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('band/'), verbose_name='Imagen principal'),
        ),
    ]
