# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0025_band_lineup_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['lineup_order', 'lineup_secondary_order'], 'verbose_name': 'Banda', 'verbose_name_plural': 'Bandas'},
        ),
        migrations.AddField(
            model_name='band',
            name='lineup_secondary_order',
            field=models.IntegerField(default=1, verbose_name='Orden en linea de cartel'),
        ),
    ]
