# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0027_news_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram'),
        ),
    ]
