# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0029_band_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivada'),
        ),
    ]
