# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-05-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0030_tag_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(related_name='band_events', to='bands.Band'),
        ),
        migrations.AlterField(
            model_name='event',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bands.Band'),
        ),
    ]
