# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-05-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0031_event_bands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='band',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_url',
            field=models.TextField(blank=True, null=True, verbose_name=b'Enlace entradas'),
        ),
    ]
